default:
  golem_name: QualidadosModulos
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/SAMUNEL/Documents/observatorio/qualidados com modulos/QualidadosModulos
